### ISSUE TITLE
Got error running the gem: `require': cannot load such file -- mysql-pr (LoadError)

### ISSUE THREAD

**Issue by samuelpismel** [maxlapshin/mysql2postgres#91]
I'm on ruby 2.3.1 and this is the build log:
```
gem install mysqltopostgres-0.3.0.gem

Fetching: test-unit-2.5.5.gem (100%)
Successfully installed test-unit-2.5.5
Fetching: postgres-pr-0.7.0.gem (100%)
Successfully installed postgres-pr-0.7.0
Fetching: mysql-pr-2.9.11.gem (100%)
Successfully installed mysql-pr-2.9.11
Successfully installed mysqltopostgres-0.3.0
4 gems installed
```
But when I run the gem this load error appears:
`/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysqltopostgres-0.3.0/lib/mysql2psql/mysql_reader.rb:4:in `require': cannot load such file -- mysql-pr (LoadError)`

Any ideas how to solve?

**Comment by onpaws** [comment]
Also encountering this error.

I installed from [source](https://github.com/maxlapshin/mysql2postgres#from-source) from inside my Rails app's directory.
Tried `gem install mysql-pr` from mysql2postgres/ as well as from within my Rails app's directory.

I also tried `bundle exec` in front but got
`gems/mysqltopostgres-0.3.0/lib/mysql2psql/mysql_reader.rb:4:in 'require': cannot load such file -- mysql-pr (LoadError)`

ruby 2.3.1, os x 10.11.6

**Comment by BKSpurgeon** [comment]
exact same error........any ideas anyone?

**Comment by hendranata** [comment]
any idea?

**Comment by anitagraham** [comment]
[This](http://stackoverflow.com/questions/28925628/ruby-on-rails-cannot-load-such-file-mysql2-2-2-mysql2-loaderror) says that the problem is related to mysql2 not being built with native extensions.  The answer gives a solution for windows, but I'll have to go and look (again) for the solution for OSX.

**Comment by jrabolli** [comment]
any luck resolving this for OSX?  I have the same issue: /.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/mysqltopostgres-0.3.1/lib/mysql2psql/mysql_reader.rb:4:in `require': cannot load such file -- mysql-pr (LoadError)

**Comment by pairmix** [comment]
Same issue with Linux Mint
What about this issue ?
