### ISSUE TITLE
You have already activated test-unit 2.5.5, but your Gemfile requires test-unit 3.2.3.

### ISSUE THREAD

**Issue by ArchTaqi** [maxlapshin/mysql2postgres#95]
I got this error on running `mysqltopostgres`

```
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:34:in `block in setup': You have already activated test-unit 2.5.5, but your Gemfile requires test-unit 3.2.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:19:in `setup'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:92:in `setup'
	from /usr/lib/ruby/vendor_ruby/bundler/setup.rb:8:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/mysqltopostgres-0.3.0/bin/mysqltopostgres:5:in `<top (required)>'
	from /usr/local/bin/mysqltopostgres:23:in `load'
	from /usr/local/bin/mysqltopostgres:23:in `<main>'

```

**Comment by dbaq** [comment]
Temporary solution that I used:

1- install by the source
```
git clone https://github.com/maxlapshin/mysql2postgres.git
cd mysql2postgres
```
2- update bundle install

replace `gem 'test-unit'` by `gem 'test-unit', '~> 2.5.5'`

3- finish install
```
bundle install
gem build mysqltopostgres.gemspec
sudo gem install mysqltopostgres-0.3.0.gem
```

Should be fine after that.

**Comment by n-rodriguez** [comment]
Fixed by https://github.com/maxlapshin/mysql2postgres/pull/97
